export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const FETCH_USER = 'FETCH_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const PASSWORD_RESET_EMAIL = 'PASSWORD_RESET_EMAIL'
export const LOGOUT = 'LOGOUT'
